version: "3"
tasks:
  init:
    summary: 開発環境の初期化
    status:
      - test -d node_modules
    cmds:
      - task: npm-ci
  update:
    summary: 開発環境の更新
    cmds:
      - task: npm-ci
  generate:
    summary: migrationファイルの生成
    aliases: ["fmt"]
    cmds:
      - npx prisma migrate dev --create-only --skip-generate
    sources:
      - prisma/schema.prisma
    generates:
      - prisma/migrations/**
  migrate:
    summary: migrationの実行
    cmds:
      - npx prisma migrate dev --skip-generate
  format:
    summary: prisma schemaファイルのformat
    aliases: ["fmt"]
    cmds:
      - npx prisma format {{.CLI_ARGS}}
  studio:
    summary: prisma studioの起動
    cmds:
      - npx prisma studio
  npm-ci:
    summary: npm ci
    sources:
      - package.json
      - package-lock.json
    cmds:
      - npm ci
