version: "3"
includes:
  migration:
    taskfile: ./migration
    dir: ./migration
  openapi:
    taskfile: ./openapi
    dir: ./openapi
tasks:
  init:
    summary: 開発環境の初期化
    deps: [install]
    status:
      - test -d node_modules
      - test -d .husky/_
    cmds:
      - task: npm-ci
  update:
    summary: 開発環境の更新
    cmds:
      - task: npm-ci
  install:
    summary: init前に必要なツールをinstallする
    preconditions:
      - go version  &> /dev/null
      - volta --version &> /dev/null
    status:
      - editorconfig-checker -version &> /dev/null
      - yamlfmt -h &> /dev/null
      - actionlint -version &> /dev/null
    cmds:
      - go install github.com/editorconfig-checker/editorconfig-checker/cmd/editorconfig-checker@latest
      - go install github.com/google/yamlfmt/cmd/yamlfmt@latest
      - go install github.com/rhysd/actionlint/cmd/actionlint@latest
  up:
    summary: 開発環境コンテナの立ち上げ
    cmds:
      - docker compose up -d
  format:
    summary: 各ファイルのフォーマット
    aliases: ["fmt"]
    cmds:
      - yamlfmt
  lint:
    summary: 各ファイルのLint
    cmds:
      - yamlfmt -lint
      - editorconfig-checker
      - actionlint
  npm-ci:
    summary: npm ci
    sources:
      - package.json
      - package-lock.json
    cmds:
      - npm ci
