version: "3"
tasks:
  init:
    summary: 開発環境の初期化
    status:
      - test -d node_modules
    cmds:
      - task: npm-ci
  update:
    summary: 開発環境の更新
    cmds:
      - task: npm-ci
  bundle:
    summary: OpenAPIファイルのbundle
    sources:
      - ./*/**.yaml
    generates:
      - bundled.yml
    cmds:
      - npx redocly bundle --output bundled.yml
  generate:
    summary: redoclyドキュメントの生成
    aliases: ["gen"]
    cmds:
      - npx redocly build-docs --output ../docs/redoc.html
    sources:
      - ./*/*.yaml
    generates:
      - ../docs/redoc.html
  lint:
    summary: OpenAPIファイルのLint
    cmds:
      - npx redocly lint
  show:
    summary: redoclyサーバー起動
    cmds:
      - npx redocly preview-docs
  npm-ci:
    summary: npm ci
    sources:
      - package.json
      - package-lock.json
    cmds:
      - npm ci
  generate-backend:
    summary: backendの生成
    sources:
      - bundled.yml
    generates:
      - ../backend/openapi/types.gen.go
      - ../backend/openapi/server.gen.go
    cmds:
      - oapi-codegen -generate types -package openapi  bundled.yml > ../backend/openapi/types.gen.go
      - oapi-codegen -generate server -package openapi  bundled.yml > ../backend/openapi/server.gen.go
