// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.2 DO NOT EDIT.
package openapi

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Defines values for TaskStatus.
const (
	Done TaskStatus = "done"
	Todo TaskStatus = "todo"
)

// Task defines model for task.
type Task struct {
	Description string              `json:"description"`
	Status      *TaskStatus         `json:"status,omitempty"`
	TaskId      *openapi_types.UUID `json:"taskId,omitempty"`
	Title       string              `json:"title"`
}

// TaskStatus defines model for Task.Status.
type TaskStatus string

// PostTasksJSONRequestBody defines body for PostTasks for application/json ContentType.
type PostTasksJSONRequestBody = Task
