name: Github Actions Lint
on:
  pull_request:
    paths:
      - ".github/workflows/**.yml"
jobs:
  actionlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-check
