ame: install
on:
  pull_request:
jobs:
  actionlint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.17
      - uses: volta-cli/action@v3
      - run: brew install go-task/tap/go-task
      - run: task install
      - run: task init
