name: Open API

on:
  - push

defaults:
  run:
    working-directory: openapi
    
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: pwd
      - run: echo ${{ github.workspace }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - run: npm ci
      - run: npm run lint