name: Open API

on:
  - push

env:
  MODULE_NAME: openapi

defaults:
  run:
    working-directory: ${{ env.MODULE_NAME }}
    
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: pwd
      - run: echo ${{ env.MODULE_NAME }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: '${{ env.MODULE_NAME }}/package.json'

      - run: npm ci
      - run: npm run lint